CREATE TABLE reviews(
    id SERIAL PRIMARY KEY,
    user_id INT REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    anime_id INT REFERENCES animes(id) ON DELETE CASCADE ON UPDATE CASCADE,
    message TEXT
)
